apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guest-rollout-git-s
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    canary:
      analysis:
        templates:
          - templateName: guest-mixed-roll-tests
        startingStep: 1
      steps:
        - pause: {duration: 15s}
        - setWeight: 50
        - pause: {duration: 15s}
  selector:
    matchLabels:
      app: guest-app-git-s
  template:
    metadata:
      labels:
        app: guest-app-git-s
    spec:
      containers:
        - name: guest-app-git-s
          image: xeonalex/guesbook:0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
