apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guesbook-prod
  labels:
    in-product: "true"
    sdasd: 'dsdsd'
  annotations: 
    codefresh.io/product: helm-restricted-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: test
  source:
    path: products/helm-guestbook-prod
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    name: in-cluster
    namespace: guestbook-prod
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      # selfHeal: true
    retry: {}
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
