apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-without-target-revision
spec:
  destination:
    namespace: test-ns
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: node
    targetRevision: 19.1.7
  project: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry: {}
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false