apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-source
  namespace: cf-apps-sources
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: nested-app
    repoURL: https://github.com/oleksandr-codefresh/eks-local_git-source
    targetRevision: personal-eks
  destination:
    name: in-cluster
    namespace: test-dev
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
