apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: waves-appset
spec:
  generators:
  - clusters: {} # This is a generator, specifically, a cluster generator.
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: '{{name}}-waves'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
        targetRevision: personal-eks
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: argocd-app-set
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
