apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-load-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: dev
    repoURL: https://github.com/oleksandr-codefresh/argo-load-product-1
    targetRevision: main
  destination:
    name: alina
    namespace: test-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
