apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gas
  namespace: eks-local
spec:
  generators:
  - list:
      elements:
      - namespace: 100
  template:
    metadata:
      name: 'guestbook-{{namespace}}'
    spec:
      project: default
      source:
        path: guestbook
        repoURL: https://github.com/pasha-codefresh/argocd-example-apps
        targetRevision: HEAD
      destination:
        name: pashaprod
        namespace: 'guestbook-{{namespace}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
