apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: dsd
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-cc2c472a-1fae-4418-8bbd-a3e0e8d6c80c:
      events:
        - push
      repositories:
        - owner: testcodefresh
          names:
            - argocd-example-apps
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/helm-01/dsd/github-cc2c472a-1fae-4418-8bbd-a3e0e8d6c80c
        url: https://alex-hermes-local.rnd.sandbox.codefresh.io
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
