apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-canary-2
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: canary-rollout
    repoURL: https://github.com/testcodefresh/argocd-example-apps
    targetRevision: test-alex
  destination:
    name: alina
    namespace: test-ns2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
