apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: earth2
  annotations: 
    codefresh.io/product: solar
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: empty2
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    server: https://kubernetes.default.svc
    # name: alina
    namespace: dev-incluster-1
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
