apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guesbook-dev-roll
  annotations: 
    codefresh.io/app-group: 'guestbook, dev'
    codefresh.io/product: B01
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: guestbooks/guestbook-rollout
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    # name: in-cluster
    name: alina
    namespace: test-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
