apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: production
  name: guest-appset
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://1.2.3.4
  # generators:
  #   - git:
  #       files:
  #         - path: dis/**/prd-us-east-1/deploy-helm.yaml
  #       repoURL: >-
  #         https://gitlab.com/preciselydata/di-suite-saas-platform/devops/gitops-deployments.git
  #       revision: HEAD
  template:
    metadata:
      name: guesbook-prod-roll
    spec:
      destination:
        name: in-cluster
        # name: alina
        namespace: test-dev
      ignoreDifferences:
        - group: apps
          jsonPointers:
            - /spec/replicas
          kind: Rollout
      project: default
      revisionHistoryLimit: 5
      source:
        path: guestbooks/guestbook-rollout
        repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
        targetRevision: personal-eks
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            policy.sigstore.dev/include: 'false'
        retry:
          limit: 3
        syncOptions:
          - CreateNamespace=true