apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guesbook-prod
  annotations: 
    codefresh.io/app-group: 'guestbook, prod'
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: guestbook-2
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    name: in-cluster
    namespace: test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
