apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guest
  annotations: 
    codefresh.io/app-group: 'test'
  finalizers:
    # - resources-finalizer.argocd.argoproj.io/foreground
    - resources-finalizer.argocd.argoproj.io/non_cascading
spec:
  project: default
  source:
    path: helm-guestbook
    helm:
      releaseName: guest
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    name: in-cluster
    namespace: test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
