apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-git-source-1
spec:
  project: default
  source:
    path: helm-guestbook-git-source
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    namespace: eks-local
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
