apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-without-revision
spec:
  destination:
    namespace: test-ns
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: node
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
