apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-rollout
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/app-group: test,g2
spec:
  project: default
  source:
    path: examples/istio
    repoURL: https://github.com/oleksandr-codefresh/rollouts-demo
    targetRevision: 1.23k8s
  destination:
    name: alina
    namespace: test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=true
  # ignoreDifferences:
  #   - group: networking.istio.io
  #     kind: VirtualService
  #     jsonPointers:
  #       - /spec/http/0
