apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-rollout
  annotations: 
    codefresh.io/app-group: 'test, g2'
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: examples/istio
    repoURL: https://github.com/oleksandr-codefresh/rollouts-demo
    targetRevision: 1.23k8s
  destination:
    # name: in-cluster
    name: alina
    namespace: test-ns
  ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec/http/0
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - RespectIgnoreDifferences=true
