apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
spec:
  destination:
    name: in-cluster
    namespace: istio
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.6
    chart: gateway
  project: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false