apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sadsd
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-de6f98f0-ab8c-4a7c-9f8a-07fc0ecf27b5:
      events:
        - push
      repositories:
        - owner: oleksandr-codefresh
          names:
            - argocd-example-apps
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/helm-01/sadsd/github-de6f98f0-ab8c-4a7c-9f8a-07fc0ecf27b5
        url: https://alex-hermes-local.rnd.sandbox.codefresh.io
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
