apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-test-app-2
spec:
  project: default
  source:
    path: helm-guestbook-git-source
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    name: in-cluster
    namespace: eks-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
