apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps.git
    targetRevision: personal-eks
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
