apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: byoa-3
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-97d8f6b3-9249-4264-b3e8-001de31fa517:
      events:
        - create
      repositories:
        - owner: codefresh-io
          names:
            - argo-platform
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/argocd/byoa-3/github-97d8f6b3-9249-4264-b3e8-001de31fa517
        url: https://1861a18a7fc8.ngrok.app
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
