apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: byoa
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-0a606afa-6976-4b1e-87fb-0d86068a5352:
      events:
        - push
      repositories:
        - owner: testcodefresh
          names:
            - argocd-example-apps
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/argocd/byoa/github-0a606afa-6976-4b1e-87fb-0d86068a5352
        url: https://1861a18a7fc8.ngrok.app
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
    github-2f74c98a-5930-415e-bee8-24da77b7d2d1:
      events:
        - commit_comment
      repositories:
        - owner: codefresh-io
          names:
            - codefresh-gitops-operator
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/argocd/byoa/github-2f74c98a-5930-415e-bee8-24da77b7d2d1
        url: https://1861a18a7fc8.ngrok.app
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
