apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byoa-guest-rollout
  annotations:
    codefresh.io/product: helm-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: guest-rollout-unexisted
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    name: in-cluster
    # name: ue1-e2e
    namespace: runtime-dev-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
