apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sadas
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
      eventName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
      eventSourceName: sadas
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: asdasd
        conditions: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: sadas-asdasd-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: CONTEXT
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: asdas
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dasdas
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dasd
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dad
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: adad
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dsads
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: asda
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dasdas
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dasdas
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dasdas
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: adsasd
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-dd0aa661-5fbf-40f0-ac64-7e2a625cc286
                dataTemplate: dasda
