apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: tes
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-9ef2fece-ff3f-424d-8d60-d70769cf2276:
      events:
        - push
      repositories:
        - owner: codefresh-io
          names:
            - cluster-desired-state
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/argocd/tes/github-9ef2fece-ff3f-424d-8d60-d70769cf2276
        url: https://1861a18a7fc8.ngrok.app
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
