apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-sample-app
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  source:
    path: guestbooks/guestbook
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks 
  project: default  # Replace 'default' with the name of the Argo CD project you want to use
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
