apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: mars-rollout2
  labels:
    testLabel: 'newvalue'
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    canary:
      steps:
        - pause: {duration: 50}
  selector:
    matchLabels:
      app: express-microservice2
  template:
    metadata:
      labels:
        app: express-microservice2
    spec:
      containers:
        - name: express-microservice2
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          ports:
            - containerPort: 3070
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
