apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-rollout-git-s
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: express-app-git-s
  template:
    metadata:
      labels:
        app: express-app-git-s
    spec:
      containers:
        - image: xeonalex/guesbook:0.2
          name: express-app-git-s
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      analysis:
        templates:
          - templateName: exp-pass-always-git-s
        startingStep: 1 # delay starting analysis run until setWeight: 40%
      steps:
        - setWeight: 25
        - pause: {duration: 15s}
        - analysis:
            templates:
            - templateName: exp-mixed-tests-git-s
