apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unexisting-helm-source-repo
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/unexisting-helm-source-repo'
    targetRevision: 15.5.2
    chart: nginx
  destination:
    name: in-cluster
    namespace: test-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
