apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-template
spec:
  applicationSourceSelector:
    matchExpressions:
      - key: in-product
        operator: Exists
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: appVersion
  promotion:
    values.yaml:
      jsonPaths:
        - $..image