apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.22
    helm:
      valuesObject:
        configs:
          cm:
            accounts.admin: apiKey,login
          params:
            server.insecure: true
            server.basehref: /argocd
            server.rootpath: /argocd
            controller.log.level: debug
        extraObjects:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              annotations:
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
              name: argocd-server
            spec:
              ingressClassName: nginx-public
              rules:
                - host: alex-byoa.rnd.sandbox.codefresh.io
                  http:
                    paths:
                      - backend:
                          service:
                            name: argocd-server
                            port:
                              number: 80
                        path: /argocd
                        pathType: Prefix
  destination:
    name: in-cluster
    # name: ue1-e2e
    namespace: argocd
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
