apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    argocd.argoproj.io/instance: test-date-default-git-source
  name: byoa-ms-canary-date
spec:
  destination:
    name: in-cluster
    namespace: test-ms-namespace
  project: default
  sources:
    - path: multi-source/canary-rollout/part-one
      repoURL: https://github.com/testcodefresh/argocd-example-apps.git
      targetRevision: master
    - path: multi-source/canary-rollout/part-two
      repoURL: https://github.com/testcodefresh/argocd-example-apps.git
      targetRevision: master
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
