apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boya-guesbook-prod-roll-multi
  annotations: 
    codefresh.io/app-long-sync-minutes: '1' # comment
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
    - path: gs-rollout-multisourced/ref
      repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
      targetRevision: multisource-ref
      ref: test
    - path: guestbooks/guestbook-rollout-multisourced/part-one
      repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
      targetRevision: personal-eks
    - path: gs-rollout-multisourced/part-two
      repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
      targetRevision: multisource-2
    - path: multi-sourced-apps-parts/gs-rollout-part-3
      repoURL: https://github.com/oleksandr-codefresh/eks-local_git-source
      targetRevision: main
  destination:
    name: in-cluster
    # name: alina
    namespace: multi-test-dev
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry: {}
    syncOptions:
      # - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
